### ISSUE TITLE
Criar rota para retornar dados do usuário

### ISSUE THREAD

**Issue by GuilhermehChaves** [grabsks/uLift-API#15]
Blocked by: #5

**Comment by luanfonsecap** [comment]
Para que eu consiga fazer essa issue totalmente o banco precisa já estar armazenando a foto de perfil do usuário (Issue #37).
Ou já deixo a rota pronta e depois incluo o retorno da imagem ?

**Comment by GuilhermehChaves** [comment]
> Para que eu consiga fazer essa issue totalmente o banco precisa já estar armazenando a foto de perfil do usuário (Issue #37).
> Ou já deixo a rota pronta e depois incluo o retorno da imagem ?

Na verdade ela é só pra retornar os dados do usuário mesmo, a de retornar as imagens seria uma outra issue, porém para retornar o telefone e o CPF, a minha PR que está aberta precisa ser aprovada

**Comment by luanfonsecap** [comment]
Em qualquer local do frontend que eu vou precisar dos dados do usuário preciso da foto de perfil também. Não tem nenhum design componente que renderiza somente dados do usuário sem a foto.

**Comment by luanfonsecap** [comment]
> > Para que eu consiga fazer essa issue totalmente o banco precisa já estar armazenando a foto de perfil do usuário (Issue #37).
> > Ou já deixo a rota pronta e depois incluo o retorno da imagem ?
> 
> Na verdade ela é só pra retornar os dados do usuário mesmo, a de retornar as imagens seria uma outra issue, porém para retornar o telefone e o CPF, a minha PR que está aberta precisa ser aprovada

Em qualquer local do frontend que eu vou precisar dos dados do usuário preciso da foto de perfil também. Não tem nenhum design componente que renderiza somente dados do usuário sem a foto.

**Comment by GuilhermehChaves** [comment]
> > > Para que eu consiga fazer essa issue totalmente o banco precisa já estar armazenando a foto de perfil do usuário (Issue #37).
> > > Ou já deixo a rota pronta e depois incluo o retorno da imagem ?
> > 
> > 
> > Na verdade ela é só pra retornar os dados do usuário mesmo, a de retornar as imagens seria uma outra issue, porém para retornar o telefone e o CPF, a minha PR que está aberta precisa ser aprovada
> 
> Em qualquer local do frontend que eu vou precisar dos dados do usuário preciso da foto de perfil também. Não tem nenhum design componente que renderiza somente dados do usuário sem a foto.

É só recuperar a foto em outra issue também
