### ISSUE TITLE
Adicionar validação de CNH

### ISSUE THREAD

**Issue by GuilhermehChaves** [grabsks/uLift-API#25]

**Comment by luanfonsecap** [comment]
Como vamos fazer a validação ?

**Comment by GuilhermehChaves** [comment]
> Como vamos fazer a validação ?

Acho que por agora não vai precisar, tem que ser quando o usuário for cadastrar uma CNH.
Mas o ideal seria achar uma lib que faz isso

**Comment by YuriAsthar** [comment]
regex para validar o formato apenas:
 /(^\d{3}\.\d{3}\.\d{3}\-\d{2}$)|(^\d{2}\.\d{3}\.\d{3}\/\d{4}\-\d{2}$)/

**Comment by YuriAsthar** [comment]
Doc https://github.com/mariohmol/js-brasil

**Comment by YuriAsthar** [comment]
bliblioteca do validador de cpf https://www.npmjs.com/package/node-cpf
