### ISSUE TITLE
Adicionar validação de senha (Letra maiúscula, números, caracteres especiais)

### ISSUE THREAD

**Issue by GuilhermehChaves** [grabsks/uLift-API#26]
No Controller do usuário, fazer uma verificação usando regex para verificar se a senha contém pelo menos um número, uma letra maiúscula, e um caractere especial.

Ex: 
`!/[a-z]/gm.test(password)`

**Comment by Nathanno11** [comment]
> No Controller do usuário, faça uma verificação usando o regex para verificar se a senha contém pelo menos um número, uma letra maiúscula e um caractere especial.
> 
> Ex:
> `!/[a-z]/gm.test(password)`
