### ISSUE TITLE
Criar rota de criação do usuário

### ISSUE THREAD

**Issue by GuilhermehChaves** [grabsks/uLift-API#5]
Defina a rota como `POST /v1/users` que receberá como parâmetro os dados do usuário, irá salvar no banco de dados e retornar o status da requisição e os dados do usuário cadastrado (com exceção da senha).

Blocked by: #4 #11 
Blocking: #25 #26 #27 #35

**Comment by Hermes-Francisco** [comment]
comecei a fazer
